/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness/readiness: proceso + conexión a la BD */
    get: operations['HealthController_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Iniciar sesión (rate limit por IP) */
    post: operations['AuthController_login_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Renovar tokens (el refresh token usado queda revocado) */
    post: operations['AuthController_refresh_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cerrar sesión (revoca el refresh token) */
    post: operations['AuthController_logout_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Perfil, rol y permisos vigentes del usuario */
    get: operations['AuthController_me_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar usuarios (paginado, sin contraseñas) */
    get: operations['UsersController_findAll_v1'];
    put?: never;
    /** Crear usuario (corrige B1: ya no es público) */
    post: operations['UsersController_create_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/me/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Cambiar mi contraseña (exige la contraseña actual) */
    patch: operations['UsersController_changeMyPassword_v1'];
    trace?: never;
  };
  '/api/v1/users/{code}/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Resetear la contraseña de un usuario (admin) */
    patch: operations['UsersController_resetPassword_v1'];
    trace?: never;
  };
  '/api/v1/users/{code}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Activar/desactivar un usuario */
    patch: operations['UsersController_setStatus_v1'];
    trace?: never;
  };
  '/api/v1/users/{code}/role': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Cambiar el rol de un usuario (revoca sus sesiones; el rol aplica al re-login) */
    patch: operations['UsersController_setRole_v1'];
    trace?: never;
  };
  '/api/v1/identity-types': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar tipos de identificación */
    get: operations['IdentityTypesController_findAll_v1'];
    put?: never;
    /** Crear tipo de identificación */
    post: operations['IdentityTypesController_create_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity-types/{code}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consultar un tipo de identificación */
    get: operations['IdentityTypesController_findOne_v1'];
    put?: never;
    post?: never;
    /** Eliminar tipo de identificación (implementa F16; 409 si tiene asociados) */
    delete: operations['IdentityTypesController_remove_v1'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/note-types': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar tipos de pagaré */
    get: operations['NoteTypesController_findAll_v1'];
    put?: never;
    /** Crear tipo de pagaré */
    post: operations['NoteTypesController_create_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/note-types/{code}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consultar un tipo de pagaré */
    get: operations['NoteTypesController_findOne_v1'];
    put?: never;
    post?: never;
    /** Eliminar tipo de pagaré (repara F19; 409 si tiene pagarés) */
    delete: operations['NoteTypesController_remove_v1'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/associates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar asociados con paginación, búsqueda y orden (F6; el "límite 6" del legacy = ?size=6&sort=updatedAt:desc) */
    get: operations['AssociatesController_findAll_v1'];
    put?: never;
    /** Registrar asociado (F5) */
    post: operations['AssociatesController_create_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/associates/{numberIdentity}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consultar asociado por identificación (F7) */
    get: operations['AssociatesController_findOne_v1'];
    /** Actualizar asociado (F8) */
    put: operations['AssociatesController_update_v1'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/notes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar pagarés con relaciones, paginado (F10); ?associateId= filtra por deudor (F11) */
    get: operations['NotesController_findAll_v1'];
    put?: never;
    /** Registrar pagaré (F9; 409 si duplicado, garantizado por la BD) */
    post: operations['NotesController_create_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/notes/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detalle de pagaré (F12) */
    get: operations['NotesController_findOne_v1'];
    put?: never;
    post?: never;
    /** Eliminar pagaré (F13): soft delete con registro de quién eliminó */
    delete: operations['NotesController_remove_v1'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    LoginDto: {
      /** @example jperez */
      username: string;
      /** @example MiClave.123 */
      password: string;
    };
    AuthUserDto: {
      code: string;
      username: string;
      names: string;
      surnames: string;
      /** @example OPERATOR */
      role: string;
      /**
       * @example [
       *       "notes:read",
       *       "notes:create"
       *     ]
       */
      permissions: unknown[][];
    };
    AuthTokensDto: {
      /** @description Access token JWT (Bearer), expira en minutos */
      accessToken: string;
      /** @description Refresh token opaco, de un solo uso (se rota en /refresh) */
      refreshToken: string;
      user: components['schemas']['AuthUserDto'];
    };
    RefreshTokenDto: {
      /** @description Refresh token entregado en login/refresh */
      refreshToken: string;
    };
    CreateUserDto: {
      /**
       * @description Código único del usuario
       * @example USR010
       */
      code: string;
      /** @example Juan Carlos */
      names: string;
      /** @example Pérez Gómez */
      surnames: string;
      /** @example jperez */
      username: string;
      /** @example Clave.Segura1 */
      password: string;
      /**
       * @description Nombre del rol (según catálogo de roles)
       * @example OPERATOR
       */
      role: string;
      /** @description URL o nombre de archivo de avatar */
      image?: string;
    };
    UserResponseDto: {
      code: string;
      names: string;
      surnames: string;
      username: string;
      /** @example OPERATOR */
      role: string;
      isActive: boolean;
      image?: Record<string, never> | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    PageMetaDto: {
      page: number;
      size: number;
      /** @description Total de registros que satisfacen la consulta */
      total: number;
    };
    PageDto: {
      meta: components['schemas']['PageMetaDto'];
    };
    ChangeMyPasswordDto: {
      /** @description Contraseña actual (obligatoria) */
      currentPassword: string;
      /** @example NuevaClave.2 */
      newPassword: string;
    };
    ResetPasswordDto: {
      /** @example ClaveTemporal.1 */
      newPassword: string;
    };
    UpdateUserStatusDto: {
      /** @description true = activo, false = desactivado */
      isActive: boolean;
    };
    UpdateUserRoleDto: {
      /**
       * @description Nombre del rol nuevo (según catálogo de roles)
       * @example OPERATOR
       */
      role: string;
    };
    CatalogEntryResponseDto: {
      /** @example CC */
      code: string;
      /** @example Cédula de ciudadanía */
      name: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateCatalogEntryDto: {
      /**
       * @description Código único, se normaliza a mayúsculas
       * @example CC
       */
      code: string;
      /** @example Cédula de ciudadanía */
      name: string;
    };
    CreateAssociateDto: {
      /**
       * @description Número de identificación (PK natural)
       * @example 1094123456
       */
      numberIdentity: string;
      /**
       * @description Código del tipo de identificación (catálogo)
       * @example CC
       */
      typeIdentity: string;
      /** @example María Fernanda */
      names: string;
      /** @example López */
      surname1: string;
      /** @example Torres */
      surname2?: string;
      /**
       * @description Fecha de nacimiento (YYYY-MM-DD), no puede ser futura
       * @example 1988-04-23
       */
      dateBirth: string;
      /**
       * @default ACTIVE
       * @enum {string}
       */
      status: 'ACTIVE' | 'INACTIVE';
    };
    AssociateResponseDto: {
      /** @example 1094123456 */
      numberIdentity: string;
      /** @example CC */
      typeIdentity: string;
      /** @example Cédula de ciudadanía */
      identityTypeName: string;
      names: string;
      surname1: string;
      surname2?: Record<string, never> | null;
      /**
       * @description YYYY-MM-DD
       * @example 1988-04-23
       */
      dateBirth: string;
      /** @example ACTIVE */
      status: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UpdateAssociateDto: {
      /**
       * @description Código del tipo de identificación (catálogo)
       * @example CC
       */
      typeIdentity: string;
      /** @example María Fernanda */
      names: string;
      /** @example López */
      surname1: string;
      /** @example Torres */
      surname2?: string;
      /**
       * @description Fecha de nacimiento (YYYY-MM-DD), no puede ser futura
       * @example 1988-04-23
       */
      dateBirth: string;
      /**
       * @default ACTIVE
       * @enum {string}
       */
      status: 'ACTIVE' | 'INACTIVE';
    };
    CreateNoteDto: {
      /**
       * @description Identificación del asociado deudor
       * @example 1094123456
       */
      associateId: string;
      /**
       * @description Código del tipo de pagaré (catálogo)
       * @example LIBRE
       */
      typeNote: string;
      /** @description Identificación del primer codeudor (asociado) */
      codeudor1Id?: string;
      /** @description Identificación del segundo codeudor (asociado) */
      codeudor2Id?: string;
    };
    NoteAssociateSummaryDto: {
      /** @example 1094123456 */
      numberIdentity: string;
      names: string;
      surname1: string;
      surname2?: Record<string, never> | null;
    };
    NoteTypeSummaryDto: {
      /** @example LIBRE */
      code: string;
      /** @example Inversión libre */
      name: string;
    };
    NoteResponseDto: {
      id: number;
      associate: components['schemas']['NoteAssociateSummaryDto'];
      noteType: components['schemas']['NoteTypeSummaryDto'];
      /**
       * @description Fecha del pagaré (YYYY-MM-DD)
       * @example 2026-03-01
       */
      noteDate: string;
      codeudor1?: components['schemas']['NoteAssociateSummaryDto'] | null;
      codeudor2?: components['schemas']['NoteAssociateSummaryDto'] | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Health Check is successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example ok */
            status?: string;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /** @example {} */
            error?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
      /** @description The Health Check is not successful */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example error */
            status?: string;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect"
             *       }
             *     }
             */
            error?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       },
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect"
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
    };
  };
  AuthController_login_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthTokensDto'];
        };
      };
    };
  };
  AuthController_refresh_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthTokensDto'];
        };
      };
    };
  };
  AuthController_logout_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenDto'];
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_me_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthUserDto'];
        };
      };
    };
  };
  UsersController_findAll_v1: {
    parameters: {
      query?: {
        /** @description Página (desde 1) */
        page?: number;
        /** @description Tamaño de página */
        size?: number;
        /** @description Filtra por nombre, apellido o username (contiene) */
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PageDto'];
        };
      };
    };
  };
  UsersController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseDto'];
        };
      };
    };
  };
  UsersController_changeMyPassword_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangeMyPasswordDto'];
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_resetPassword_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordDto'];
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_setStatus_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserStatusDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseDto'];
        };
      };
    };
  };
  UsersController_setRole_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserRoleDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseDto'];
        };
      };
    };
  };
  IdentityTypesController_findAll_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CatalogEntryResponseDto'][];
        };
      };
    };
  };
  IdentityTypesController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCatalogEntryDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CatalogEntryResponseDto'];
        };
      };
    };
  };
  IdentityTypesController_findOne_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CatalogEntryResponseDto'];
        };
      };
    };
  };
  IdentityTypesController_remove_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NoteTypesController_findAll_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CatalogEntryResponseDto'][];
        };
      };
    };
  };
  NoteTypesController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCatalogEntryDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CatalogEntryResponseDto'];
        };
      };
    };
  };
  NoteTypesController_findOne_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CatalogEntryResponseDto'];
        };
      };
    };
  };
  NoteTypesController_remove_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AssociatesController_findAll_v1: {
    parameters: {
      query?: {
        /** @description Página (desde 1) */
        page?: number;
        /** @description Tamaño de página */
        size?: number;
        /** @description Filtra por nombre, apellidos o identificación (contiene) */
        search?: string;
        /** @description Orden `campo:direccion`. El "límite 6" del legacy equivale a ?size=6&sort=updatedAt:desc */
        sort?:
          | 'updatedAt:desc'
          | 'updatedAt:asc'
          | 'createdAt:desc'
          | 'createdAt:asc'
          | 'names:asc'
          | 'names:desc'
          | 'numberIdentity:asc'
          | 'numberIdentity:desc';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PageDto'];
        };
      };
    };
  };
  AssociatesController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateAssociateDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssociateResponseDto'];
        };
      };
    };
  };
  AssociatesController_findOne_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        numberIdentity: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssociateResponseDto'];
        };
      };
    };
  };
  AssociatesController_update_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        numberIdentity: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAssociateDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AssociateResponseDto'];
        };
      };
    };
  };
  NotesController_findAll_v1: {
    parameters: {
      query?: {
        /** @description Página (desde 1) */
        page?: number;
        /** @description Tamaño de página */
        size?: number;
        /** @description Filtra los pagarés de un asociado (deudor) */
        associateId?: string;
        /** @description Fecha del pagaré desde (inclusive) */
        dateFrom?: string;
        /** @description Fecha del pagaré hasta (inclusive) */
        dateTo?: string;
        /** @description Orden `campo:direccion` */
        sort?:
          'noteDate:desc' | 'noteDate:asc' | 'createdAt:desc' | 'createdAt:asc';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PageDto'];
        };
      };
    };
  };
  NotesController_create_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateNoteDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NoteResponseDto'];
        };
      };
    };
  };
  NotesController_findOne_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NoteResponseDto'];
        };
      };
    };
  };
  NotesController_remove_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
